vich_uploader:
    db_driver: orm

    mappings:
        act_picture:
            uri_prefix: /uploads/act
            upload_destination: '%kernel.project_dir%/public/uploads/act'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        spectacle_picture:
            uri_prefix: /uploads/spectacle
            upload_destination: '%kernel.project_dir%/public/uploads/spectacle'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
